name: AUTO-CHECKIN    
on:
  push:
    branches: [ master ]
    paths-ignore: 
      - 'README.md'
  workflow_dispatch:
  schedule:
    - cron: 20 3 * * *
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@master
        with:
          python-version: 3.8

      - name: install dependencies
        run: pip install httpx

      - name: checkin
        env:
          CHICKEN_MAIL: ${{ secrets.CHICKEN_MAIL }}
          CHICKEN_PASSWORD: ${{ secrets.CHICKEN_PASSWORD }}
        run: python gittest.py
